name: pointset_image_recognition
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cudatoolkit=10.0.130
  - freetype=2.9.1
  - intel-openmp=2020.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.1.2
  - pip=20.0.2
  - pycparser=2.20
  - python=3.6.10
  - readline=8.0
  - setuptools=46.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tqdm=4.46.0
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.2.0
  - torchvision=0.4.0
  - pip:
    - absl-py==0.9.0
    - ase==3.19.1
    - cachetools==4.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - future==0.18.2
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - googledrivedownloader==0.4
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - importlib-metadata==1.6.0
    - isodate==0.6.0
    - joblib==0.15.1
    - kiwisolver==1.2.0
    - llvmlite==0.33.0
    - markdown==3.2.2
    - matplotlib==3.2.1
    - networkx==2.4
    - numba==0.50.0
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - pandas==1.0.4
    - plyfile==0.7.2
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - rdflib==5.0.0
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - tb-nightly==2.3.0a20200513
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==2.0
    - threadpoolctl==2.0.0
    - torch==1.2.0
    - torch-cluster==1.4.3
    - torch-geometric==1.3.1
    - torch-scatter==1.2.0
    - torch-sparse==0.4.4
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - zipp==3.1.0

